### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dyjs-js** [dyjs-js/shooting_game#1]
1. LIFE 만들기
2. 적의 미사일을 플레이어가 맞았을때 충돌 함수 처리 ClashEnemyAndBullet()
3. 적 공격 성공 시 점수 표시
-- 
하면 좋을것
1. 필살기 (추가미사일) 만들기

**Comment by dyjs-js** [comment]
- [ v ] LIFE 만들기 4/6
- [ v ] 적의 미사일을 플레이어가 맞았을때 충돌 함수 처리 ClashEnemyAndBullet() 4/6
- [ ] hp 다 소진시 어떻게 할지 생각해보기 -> 바로 종료 혹은 기록..
- [ ] 충돌되면 화면에 출력하는거를 gotoxy가 아니라 바로 출력하는게 좋을거같음
- [ ] 적 공격 성공 시 점수 표시 
- [ ] 필살기 (추가미사일) 만들기

**Comment by dyjs-js** [comment]
- [ v ]  LIFE 만들기 4/6
- [ v ]  적의 미사일을 플레이어가 맞았을때 충돌 함수 처리 ClashEnemyAndBullet() 4/6
- [ v ]  hp 다 소진시 어떻게 할지 생각해보기 -> 바로 종료 혹은 기록.. --> 종료 및 스코어 표시 4/16
- [ v ]  충돌되면 화면에 출력하는거를 gotoxy가 아니라 바로 출력하는게 좋을거같음--> 출력이 아닌 화면 깜빡임으로 처리 4/16
- [ v ]  적 공격 성공 시 점수 표시 --> 상단에 스코어 표시 4/16
- [ ]  필살기 (추가미사일) 만들기
- [ ]  2단계 만들기
